### PR TITLE
Drawing on wrong frame

### LINKED ISSUE #42: Drawing appear on the wrong frame while playing a video

### PR DESCRIPTION
**Pull request by henpe071**
Videoplayer was processing the frame before updating the frame number, which means the drawings on the overlay were drawn on the wrong frame while video is playing.

Fixes #42

### CODE REVIEW

**Comment by klwing021** [comment]
If an object is selected, the bounding-box is still drawn on the wrong frame

**Comment by niklasniklas** [comment]
Works fine!

File: ViAn/Video/videoplayer.cpp [hunk 1]
```diff
@@ -125,10 +125,16 @@ void VideoPlayer::check_events() {
             // Timer condition triggered. Read new frame
             if (m_is_playing->load()) {
                 std::chrono::steady_clock::time_point start = std::chrono::steady_clock::now();
-                if (!synced_read()) continue;
                 ++*m_frame;
```
Comment (fredrikiselius) [inline ViAn/Video/videoplayer.cpp:130]: We should add a comment here of why we are doing it this way.
