### PR TITLE
Prevent crash when closing project while analysis is running

### LINKED ISSUE #73: Remove queued analysis
There is a remove option for queued analysis items in the project widget that crashes the program

### PR DESCRIPTION
**Pull request by henpe071**
Removed some options from the context menu before the analysis is done.
Now when the project would be closed it prompts the user if it wants to abort all the current running analyses, if not just cancel.

fix #73 and #19 .

### CODE REVIEW

**Comment by niklasniklas** [comment]
Works! :-)

File: ViAn/GUI/Analysis/analysiswidget.cpp [hunk 1]
```diff
@@ -94,17 +94,25 @@ void AnalysisWidget::abort_analysis() {
...
+void AnalysisWidget::abort_all_analysis() {
+    abort_all = true;
+    abort_analysis();
+}
+
 void AnalysisWidget::on_analysis_aborted() {
     analysis_queue.pop_front();
     delete current_analysis_item; // Delete item from tree
-    auto it = abort_map.find(current_method);   
+    auto it = abort_map.find(current_method);
```
Comment (fredrikiselius) [inline ViAn/GUI/Analysis/analysiswidget.cpp]: Should only erase the `current_method` is actually found otherwise this could lead to problems 
`if (it != abort_map.end())`

**Review by fredrikiselius — COMMENTED** [review]
New additions works as they should. I noticed a quite large increase in memory usage after canceling an analysis though. Is this to be expected or do we have a memory leak here? Either way it caused a crash for me, we need to catch the error in the analysis loop

**Comment by henpe071** [comment]
There seems to be some memory that's not cleared when an analysis is removed. What was the crash you got? Works for me.

**Comment by fredrikiselius** [comment]
I have quite limited memory on the computer I'm currently on so when I started two analyses and canceled the first on there wasn't enough memory left for opencv to allocate for the next video so it threw a memory allocation error. Either way it needs to be solved. Should we make it part of this branch or add it as another issue and fix it in another?

**Comment by henpe071** [comment]
I tried with some other videos and with one of them I get memory error even when i queue it with another video. There can definitely be some things done on the analysis code but again I think we should do it in a seperate branch when it's not directly releted to the pull request.

**Comment by fredrikiselius** [comment]
I'll create another issue then (#91) and merge this one
